[package]
name = "propcalc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.4"
indicatif = "0.17.1"
inquire = "0.3.0"
